<?php
/**
 * underscore.js template for each item in the dialog to insert a Toolset Form scaffold.
 *
 * @since m2m
 */
?>
<script type="text/html" id="tmpl-cred-editor-scaffold-item">
	<#
	data = _.extend(
		{ attributes: {}, options: {}, requiredItem: false },
		data
	);
	#>
	<li class="cred-editor-scaffold-item-container js-cred-editor-scaffold-item-container" 
		data-shortcode="{{data.shortcode}}" 
		data-fieldtype="{{data.fieldType}}" 
		data-label="{{data.label}}" 
		data-attributes="<# print( _.escape( ( JSON.stringify( data.attributes ) ) ) ); #>" 
		data-options="<# print( _.escape( ( JSON.stringify( data.options ) ) ) ); #>" 
		data-include="true"
	>
		<i class="fa fa-arrows cred-editor-scaffold-item-move js-cred-editor-scaffold-item-move" title="<?php echo esc_attr( __( 'Change position', 'wp-cred' ) ); ?>"></i>
		<# if ( data.requiredItem ) { #>
			<i class="fa fa-lock fa-fw cred-editor-scaffold-item-required" title="<?php echo esc_attr( __( 'Required', 'wp-cred' ) ); ?>"></i>
		<# } else { #>
			<i class="fa fa-eye fa-fw cred-editor-scaffold-item-include-toggle js-cred-editor-scaffold-item-include-toggle" title="<?php echo esc_attr( __( 'Toggle element', 'wp-cred' ) ); ?>"></i>
		<# } #>
		{{{data.label}}}
		<# print( data.templates.scaffold.itemOptions( data ) ); #>
	</li>
</script>